name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.3"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run Tests
        run: make test
      
      - name: Run Lint Check
        run: make lint
